version: "3.8"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: case_study
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  scraper-api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://user:password@postgres:5432/case_study
